name: Auto Merge Owner

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.actor == 'automate6500' || github.actor == 'octocat'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: pip install -r requirements.txt
