name: Auto Merge Owner

on:
  pull_request:
    types: [opened]

jobs:
  lint:
    if: github.actor == 'automate6500' || github.actor == 'octocat'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: flake8 and pylint
      run: |
        pip install -r requirements.txt
        flake8 --ignore=E501,E231 *.py tests/*.py
        pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
    - name: unit test
      run: python -m unittest --verbose --failfast
  merge:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: pascalgn/automerge-action@v0.6.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
